refugee/app/urls.py
from . import views
from django.conf.urls import url

app_name = 'app'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^ngo_register/$', views.ngo_register, name='ngo_register'),
    url(r'^user_register/$', views.register, name='register'),
    url(r'^user_login/$', views.login, name='login'),
    url(r'^user_logout/$', views.logout, name='logout'),
    url(r'^ngo_login/$', views.ngo_login, name='ngo_login'),
    url(r'^ngo_profile/(?P<pk>[0-9]+)/$', views.ngo_profile, name='ngo_profile'),
    url(r'^ngo_logout/$', views.ngo_logout, name='ngo_logout'),
    url(r'^refugee_profile/(?P<idx>[0-9]+)/$', views.profile, name='profile'),
    url(r'^all_petitions/$', views.all_petition, name='all_petition'),
    url(r'^petition/ngo/create/$', views.create_ngo_petition, name='create_ngo_petition'),
    url(r'^petition/ngo/(?P<pk>[0-9]+)/$', views.view_ngo_petition, name='view_ngo_petition'),
    url(r'^petition/ngo/(?P<pk>[0-9]+)/vote/$', views.vote_ngo_petition, name='vote_ngo_petition'),
    url(r'^vote_message/$', views.vote_message, name='vote_message'),
    url(r'^petition/ngo/vote/(?P<pk>[0-9]+)/success/$', views.confirm_email, name='confirm'),
    url(r'^askforhelp/$', views.askforhelp, name='askforhelp'),
    url(r'^search/ngo/$', views.search_ngo, name='search_ngo'),
    url(r'^search/refugee/$', views.search_refugee, name='search_refugee'),
    url(r'^add/notification/$', views.add_notif, name='add_notif'),
    url(r'^all/notification/$', views.allnotifs, name='allnotifs'),
    url(r'^add/event/$', views.add_event, name='add_event'),
    url(r'^all/event/$', views.all_event, name='all_event'),
    url(r'^petition/refugee/create/$', views.create_refugee_petition, name='create_refugee_petition'),
    url(r'^petition/refugee/(?P<pk>[0-9]+)/$', views.view_refugee_petition, name='view_refugee_petition'),
    url(r'^petition/refugee/(?P<pk>[0-9]+)/vote/$', views.vote_refugee_petition, name='vote_refugee_petition'),
    url(r'^petition/refugee/vote/(?P<pk>[0-9]+)/success/$', views.refugee_confirm_email, name='refugee_confirm'),
]

refugee/refugee/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

refugee/app/templates/app/addevent.html
<!DOCTYPE html>
 <html>
     <head>
        <!-- Is anyone getting tired of repeatedly entering the header over and over??
        yes
         -->
         <title>Rango</title>
     </head>

     <body>

       <form method='POST'>
       {% csrf_token %}
       title <input type="text" name="title"><br>
       reason <input type="text" name="reason"><br>
       location <input type="text" name="location"><br>
       Date<input type="datetime-local" name="date">
       <input type="submit" name="Submit">
     </form>
     {% if error %}
       <p>{{ error }}</p>
     {% endif %}
     </body>
 </html>

 {% load static %}
 <!DOCTYPE html>
 <html class="no-js">
     <head>
       <meta charset="utf-8">
       <title>Contact | Charity / Non-profit responsive Bootstrap HTML5 template</title>
       <meta name="description" content="">
       <meta name="viewport" content="width=device-width, initial-scale=1">

       <!-- Fonts -->
       <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
       <link href='http://fonts.googleapis.com/css?family=Dosis:400,700' rel='stylesheet' type='text/css'>

       <!-- Bootsrap -->
       <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">

       <!-- Font awesome -->
       <link rel="stylesheet" href="{% static 'app/css/font-awesome.min.css' %}">

       <!-- Template main Css -->
       <link rel="stylesheet" href="{% static 'app/css/style.css' %}">

       <!-- Modernizr -->
       <script src="{% static 'app/js/modernizr-2.6.2.min.js' %}"></script>

     </head>

     <body>


     <header class="main-header">


         <nav class="navbar navbar-static-top navbar-fixed-top">

             <div class="navbar-top">

               <div class="container">
                   <div class="row">

                     <div class="col-sm-6 col-xs-12">

                         <ul class="list-unstyled list-inline header-contact">
                             <li> <i class="fa fa-phone"></i> <a href="tel:">+91 223 510 005 </a> </li>
                              <li> <i class="fa fa-envelope"></i> <a href="mailto:contact@sadaka.org">refuhelp@gmail.com</a> </li>
                        </ul> <!-- /.header-contact  -->

                     </div>

                     <div class="col-sm-6 col-xs-12 text-right">

                         <ul class="list-unstyled list-inline header-social">

                             <li> <a href="#"> <i class="fa fa-facebook"></i> </a> </li>
                             <li> <a href="#"> <i class="fa fa-twitter"></i>  </a> </li>
                             <li> <a href="#"> <i class="fa fa-google"></i>  </a> </li>
                             <li> <a href="#"> <i class="fa fa-youtube"></i>  </a> </li>
                        </ul> <!-- /.header-social  -->

                     </div>


                   </div>
               </div>

             </div>

             <div class="navbar-main">

               <div class="container">

                 <div class="navbar-header">
                   <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">

                     <span class="sr-only">Toggle navigation</span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>

                   </button>

                   <a class="navbar-brand" href="index.html" style="padding-top: 22px;">RefuHelp</a>

                 </div>

                 <div id="navbar" class="navbar-collapse collapse pull-right">

                   <ul class="nav navbar-nav">

                     <li><a class="is-active" href="{% url 'app:index' %}">HOME</a></li>
                     <li><a href="{% url 'app:all_petition' %}">PETITIONS</a></li>
                     <li ><a href="{% url 'app:search_ngo' %}">SEARCH</a></li>

                     {% if request.user.refugee %}
                       <li><a href="{% url 'app:profile' request.user.refugee.id %}">DASHBOARD</a></li>
                       <li><a href="{% url 'app:logout' %}">SIGN OUT</a></li>
                     {% endif %}

                     {% if request.user.ngo %}
                       <li><a href="{% url 'app:ngo_profile' request.user.ngo.id %}">DASHBOARD</a></li>
                       <li><a href="{% url 'app:ngo_logout' %}">SIGN OUT</a></li>
                     {% endif %}

                     {% if not request.user.is_authenticated %}
                       <li><a href="{% url 'app:login' %}">LOGIN</a></li>
                       <li><a href="{% url 'app:ngo_register' %}">SIGN UP AS NGO</a></li>
                     {% endif %}

                   </ul>

                 </div> <!-- /#navbar -->

               </div> <!-- /.container -->

             </div> <!-- /.navbar-main -->


         </nav>

     </header> <!-- /. main-header -->

     <div class="page-heading text-center">

         <div class="container zoomIn animated">

             <h1 class="page-title">ADD CAMPAIGNS<span class="title-under"></span></h1>
             <p class="page-description">
                 Make a difference here.
             </p>

         </div>

     </div>


     <div class="main-container fadeIn animated">
         <div class="container">
             <div class="row">
                 <div class="col-md-offset-4 col-md-5">
                     <h2 class="title-style-2">EVENT FORM <span class="title-under"></span></h2>
                     <form action="{% url 'app:add_event' %}" class="contact-form" method="post">
                       {% csrf_token %}


                         <div class="row">
                             <div class="form-group" style="margin-left: 15px;">
                                 <input type="text" name="title" class="form-control" placeholder="Title*" required>
                             </div>
                             <br/>
                             <div class="form-group" style="margin-left: 15px;">
                             <textarea name="reason" rows="5" class="form-control" placeholder="Reason*" ></textarea>
                             </div>
                             <br/>
                             <div class="form-group " style="margin-left: 15px;">
                                 <input type="text" name="location" class="form-control" placeholder="Location*" required>
                             </div>
                             <br/>
                             <div class="form-group " style="margin-left: 15px;">
                                 <label >Enter date and time for the event: </label><input class="form-control" id="party" type="datetime-local" name="date" value="2017-06-01T08:30" required>
                             </div>


                         </div>

                         <div class="form-group alerts">

                             <div class="alert alert-success" role="alert">

                             </div>

                             <div class="alert alert-danger" role="alert">

                             </div>

                         </div>


                          <div class="form-group">
                             <button type="submit" class="btn btn-primary">Add</button>
                         </div>




                         <div class="clearfix"></div>

                     </form>
                 </div>
             </div>
         </div>
     </div>


     <footer class="main-footer">




         <div class="footer-main">
             <div class="container">

                 <div class="row">
                     <div class="col-md-5">

                         <div class="footer-col">

                             <h4 class="footer-title">About us <span class="title-under"></span></h4>

                             <div class="footer-content">
                                 <p>
                                     <strong>RefuHelp</strong> stands for the Humans of Future where the world is free from wars, poverty and people suffering from it. We are a team of 4 youngsters aiming high towards SUCCESS. If you are reading this, you have no job whatsoever. Pay attention to the page< we have invested time in it
                                 </p>

                                 <p>
                                     What are you still doing here? Dont pay attention to me. Ok tata, Goodbye
                                 </p>

                             </div>

                         </div>

                     </div>

                     <div class="col-md-offset-1 col-md-5">

                         <div class="footer-col">

                             <h4 class="footer-title">LAST TWEETS <span class="title-under"></span></h4>

                             <div class="footer-content">
                                 <ul class="tweets list-unstyled">
                                     <li class="tweet">

                                         20 Surprise Eggs, Kinder Surprise Cars 2 Thomas Spongebob Disney Pixar  http://t.co/fTSazikPd4

                                     </li>

                                     <li class="tweet">

                                         20 Surprise Eggs, Kinder Surprise Cars 2 Thomas Spongebob Disney Pixar  http://t.co/fTSazikPd4

                                     </li>

                                     <li class="tweet">

                                         20 Surprise Eggs, Kinder Surprise Cars 2 Thomas Spongebob Disney Pixar  http://t.co/fTSazikPd4

                                     </li>

                                 </ul>
                             </div>

                         </div>

                     </div>


 <!--

 -->
                     <div class="clearfix"></div>



                 </div>


             </div>


         </div>

         <div class="footer-bottom">

             <div class="container text-right">
                 RefuHelp @ copyright 2018 &nbsp;  &nbsp;All rights Reserved</a>
             </div>
         </div>

     </footer>






         <!-- jQuery -->
         <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
           <script>window.jQuery || document.write('<script src="{% static 'app/js/jquery-1.11.1.min.js' %}"></script>')</script>

         <!-- Bootsrap javascript file -->
         <script src="{% static 'app/js/bootstrap.min.js' %}"></script>


         <!-- Google map  -->
         <script src="http://maps.google.com/maps/api/js?sensor=false&amp;libraries=places" type="text/javascript"></script>


         <!-- Template main javascript -->
         <script src={% static 'app/js/main.js' %}></script>

         <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
         <script>
             (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
             function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
             e=o.createElement(i);r=o.getElementsByTagName(i)[0];
             e.src='//www.google-analytics.com/analytics.js';
             r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
             ga('create','UA-XXXXX-X');ga('send','pageview');
         </script>
     </body>
 </html>

refugee/app/templates/app/list_all_petition.html
{% load static %}
<!DOCTYPE html>
<html class="no-js">
    <head>
      <meta charset="utf-8">
      <title>Contact | Charity / Non-profit responsive Bootstrap HTML5 template</title>
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- Fonts -->
      <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
      <link href='http://fonts.googleapis.com/css?family=Dosis:400,700' rel='stylesheet' type='text/css'>

      <!-- Bootsrap -->
      <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">

      <!-- Font awesome -->
      <link rel="stylesheet" href="{% static 'app/css/font-awesome.min.css' %}">

      <!-- Template main Css -->
      <link rel="stylesheet" href="{% static 'app/css/style.css' %}">

      <!-- Modernizr -->
      <script src="{% static 'app/js/modernizr-2.6.2.min.js' %}"></script>

    </head>
    <body>
    <!-- NAVBAR
    ================================================== -->

<header class="main-header">


        <nav class="navbar navbar-static-top">

            <div class="navbar-top">

              <div class="container">
                  <div class="row">

                    <div class="col-sm-6 col-xs-12">

                        <ul class="list-unstyled list-inline header-contact">
                            <li> <i class="fa fa-phone"></i> <a href="tel:">+212 658 986 213 </a> </li>
                             <li> <i class="fa fa-envelope"></i> <a href="mailto:contact@sadaka.org">contact@sadaka.org</a> </li>
                       </ul> <!-- /.header-contact  -->

                    </div>

                    <div class="col-sm-6 col-xs-12 text-right">

                        <ul class="list-unstyled list-inline header-social">

                            <li> <a href="#" target="_blank"> <i class="fa fa-facebook"></i> </a> </li>
                            <li> <a href="#" target="_blank"> <i class="fa fa-twitter"></i>  </a> </li>
                            <li> <a href="#" target="_blank"> <i class="fa fa-google"></i>  </a> </li>
                            <li> <a href="#" target="_blank"> <i class="fa fa-youtube"></i>  </a> </li>
                            <li> <a href="#" target="_blank"> <i class="fa fa fa-pinterest-p"></i>  </a> </li>

                       </ul> <!-- /.header-social  -->

                    </div>


                  </div>
              </div>

            </div>

            <div class="navbar-main">

              <div class="container">

                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">

                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>

                  </button>

                  <a class="navbar-brand" href="index.html"><img src="{% static 'app/images/sadaka-logo.png' %}" alt=""></a>

                </div>

                <div id="navbar" class="navbar-collapse collapse pull-right">

                  <ul class="nav navbar-nav">

                    <li><a class="is-active" href="{% url 'app:index' %}">HOME</a></li>
                    <li><a href="{% url 'app:all_petition' %}">PETITIONS</a></li>
                    <li ><a href="{% url 'app:search_ngo' %}">SEARCH</a></li>

                    {% if request.user.refugee %}
                      <li><a href="{% url 'app:profile' request.user.refugee.id %}">DASHBOARD</a></li>
                      <li><a href="{% url 'app:logout' %}">SIGN OUT</a></li>
                    {% endif %}

                    {% if request.user.ngo %}
                      <li><a href="{% url 'app:ngo_profile' request.user.ngo.id %}">DASHBOARD</a></li>
                      <li><a href="{% url 'app:ngo_logout' %}">SIGN OUT</a></li>
                    {% endif %}

                    {% if not request.user.is_authenticated %}
                      <li><a href="{% url 'app:login' %}">LOGIN</a></li>
                      <li><a href="{% url 'app:ngo_register' %}">SIGN UP AS NGO</a></li>
                    {% endif %}

                  </ul>

                </div> <!-- /#navbar -->

              </div> <!-- /.container -->

            </div> <!-- /.navbar-main -->


        </nav>

    </header> <!-- /. main-header -->

	<div class="page-heading text-center">

		<div class="container zoomIn animated">

			<h1 class="page-title">FILE A PETITION <span class="title-under"></span></h1>
			<p class="page-description">
				Help Support a Cause !
			</p>

		</div>

	</div>

	<div class="main-container">

		<div class="container">
      {% if request.user.refugee %}
      <a href="{% url 'app:create_refugee_petition' %}"><button type="" class="btn btn-primary" style="margin-top: 15px;">Start a Petition</button></a><br/><br/><br/>

      {% endif %}

      {% if request.user.ngo %}
      <a href="{% url 'app:create_ngo_petition' %}"><button type="" class="btn btn-primary" style="margin-top: 15px;">Start a Petition</button></a><br/><br/><br/>
      {% endif %}



  {% for petition in petition1 %}
          <a href="{% url 'app:view_ngo_petition' petition.id %}">
					<div class="col-md-3 col-sm-6">
                        <div class="cause hover">
                             <img src="{% static 'app/images/causes/tampoon.jpg' %}" alt="" class="cause-img" style="height: 190px;">
                             <h4 class="cause-title"><a href="{% url 'app:view_ngo_petition' petition.id %}">{{petition.title }} </a></h4>
                             <div class="cause-details"><br/>
                                 <b>{{ petition.description }}</b>

                                 <br/><br/><br/>
                                 <span style="font-size: 18px;"><i class="fa fa-users" aria-hidden="true"></i>{{ petition.ngo_petition_votes.count }}</span>
                             </div>
                        </div> <!-- /.cause -->
                    </div>
                    </a>
          {% endfor %}

          {% for petition in petition2 %}
                  <a href="{% url 'app:view_refugee_petition' petition.id %}">
                  <div class="col-md-3 col-sm-6">
                                <div class="cause hover">
                                     <img src="{% static 'app/images/causes/tampoon.jpg' %}" alt="" class="cause-img" style="height: 190px;">
                                     <h4 class="cause-title"><a href="{% url 'app:view_refugee_petition' petition.id %}">{{petition.title }} </a></h4>
                                     <div class="cause-details"><br/>
                                         <b>{{ petition.description }}</b>

                                         <br/><br/><br/>
                                         <span style="font-size: 18px;"><i class="fa fa-users" aria-hidden="true"></i>{{ petition.refugee_petition_votes.count }}</span>
                                     </div>
                                </div> <!-- /.cause -->
                            </div>
                            </a>
                  {% endfor %}
		</div>
	</div>


    <footer class="main-footer" style="margin-bottom: -200px;">




        <div class="footer-main">
            <div class="container">

                <div class="row">
                    <div class="col-md-5">

                        <div class="footer-col">

                            <h4 class="footer-title">About us <span class="title-under"></span></h4>

                            <div class="footer-content">
                                <p>
                                    <strong>Sadaka</strong> ipsum dolor sit amet, consectetur adipiscing elit. Ut at eros rutrum turpis viverra elementum semper quis ex. Donec lorem nulla, aliquam quis neque vel, maximus lacinia urna.
                                </p>

                                <p>
                                    ILorem ipsum dolor sit amet, consectetur adipiscing elit. Ut at eros rutrum turpis viverra elementum semper quis ex. Donec lorem nulla, aliquam quis neque vel, maximus lacinia urna.
                                </p>

                            </div>

                        </div>

                    </div>

                    <div class="col-md-offset-1 col-md-5">

                        <div class="footer-col">

                            <h4 class="footer-title">LAST TWEETS <span class="title-under"></span></h4>

                            <div class="footer-content">
                                <ul class="tweets list-unstyled">
                                    <li class="tweet">

                                        20 Surprise Eggs, Kinder Surprise Cars 2 Thomas Spongebob Disney Pixar  http://t.co/fTSazikPd4

                                    </li>

                                    <li class="tweet">

                                        20 Surprise Eggs, Kinder Surprise Cars 2 Thomas Spongebob Disney Pixar  http://t.co/fTSazikPd4

                                    </li>

                                    <li class="tweet">

                                        20 Surprise Eggs, Kinder Surprise Cars 2 Thomas Spongebob Disney Pixar  http://t.co/fTSazikPd4

                                    </li>

                                </ul>
                            </div>

                        </div>

                    </div>


<!--

-->
                    <div class="clearfix"></div>



                </div>


            </div>


        </div>

        <div class="footer-bottom">

            <div class="container text-right">
                RefuHelp @ copyright 2018 &nbsp;  &nbsp;All rights Reserved</a>
            </div>
        </div>

    </footer>
-- jQuery -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="assets/js/jquery-1.11.1.min.js"><\/script>')</script>

        <!-- Bootsrap javascript file -->
        <script src="assets/js/bootstrap.min.js"></script>


        <!-- Template main javascript -->
        <script src="assets/js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>
    </body>
</html>

refugee/app/templates/app/vote_message.html
<h1>Your vote has been recorded. Verify your email ID to confirm your vote.</h1>